graph LR
    A[Square]
    B(Round)
    C((Circle))
    D{Rhombus}
    E[[Subroutine]]
    F[(Database)]
    G{{Hexagon}}
    H[/Parallelogram/]
    I[\BackSlash\]
    J[/Trapezoid\]
    K[\InvTrapezoid/]
    L([Stadium])
    M>Asymmetric]
